import Image from "next/image";

import { gameRegistry } from "../data/game-registry";
import type { GameId, GameSceneId } from "../types";

/* -------------------------------------------------------------------------
 * Game scenes
 *
 * The illustrations behind the arcade tiles, served from `public/assets/games`
 * and regenerated by `scripts/generate-game-scenes.mjs`. Seven are ports of the
 * `CustomPainter` family in the Flutter screen; the rest are new, drawn in the
 * same language. Formats that repeat across sports — the five quizzes, the
 * mystery games — share one drawing rather than carrying near-identical files.
 *
 * These carry their own palette, so — like the brand artwork in
 * `design-system/icons/brand.tsx` — they are images rather than inlined and
 * tinted. An SVG loaded through `<img>` is its own document and cannot read the
 * page's custom properties, so the accents inside each file are the token
 * values written out. Changing an accent token means re-running the generator.
 *
 * Every file shares one viewBox, cropped to the art, so the scenes are
 * interchangeable and position identically.
 * ---------------------------------------------------------------------- */

export const gameSceneAssets: Record<GameSceneId, { src: string; alt: string }> = {
  "pitch-duel": {
    src: "/assets/games/pitch-duel.svg",
    alt: "Tactics board with a passing route",
  },
  "penalty-shootout": {
    src: "/assets/games/penalty-shootout.svg",
    alt: "Goal, target, and ball",
  },
  "football-chess": {
    src: "/assets/games/football-chess.svg",
    alt: "Five-by-five board mid-duel",
  },
  "final-over": {
    src: "/assets/games/final-over.svg",
    alt: "Cricket strip with stumps and a ball in flight",
  },
  "hoop-duel": {
    src: "/assets/games/hoop-duel.svg",
    alt: "Street basketball court in perspective",
  },
  "grand-prix-dash": {
    src: "/assets/games/grand-prix-dash.svg",
    alt: "Circuit telemetry with a car on the racing line",
  },
  "tennis-rally": {
    src: "/assets/games/tennis-rally.svg",
    alt: "Tennis court in perspective with the ball mid-air",
  },
  quiz: {
    src: "/assets/games/quiz.svg",
    alt: "Four answer options with one chosen",
  },
  bingo: {
    src: "/assets/games/bingo.svg",
    alt: "Bingo card with a winning line daubed",
  },
  "guess-player": {
    src: "/assets/games/guess-player.svg",
    alt: "Redacted player silhouette",
  },
  "guess-driver": {
    src: "/assets/games/guess-driver.svg",
    alt: "Redacted driver helmet",
  },
  "guess-winner": {
    src: "/assets/games/guess-winner.svg",
    alt: "Redacted trophy",
  },
};

/** Where each scene's wash lands at the right edge, before the fade. */
const wash: Record<GameSceneId, string> = {
  "pitch-duel": "#0a2a34",
  "penalty-shootout": "#0c3021",
  "football-chess": "#2f290b",
  "final-over": "#0b2b39",
  "hoop-duel": "#2c260d",
  "grand-prix-dash": "#361321",
  "tennis-rally": "#1b3f55",
  quiz: "#241a33",
  bingo: "#2f2109",
  "guess-player": "#301a26",
  "guess-driver": "#301a26",
  "guess-winner": "#0b2b39",
};

export type GameSceneProps = {
  game: GameId;
  /**
   * Scene opacity. Hero tiles show the art outright; quick tiles run it as a
   * watermark behind their type.
   */
  opacity?: number;
  /** Lays the accent wash under the art. Off for watermark use. */
  washed?: boolean;
};

/**
 * The painted backdrop for a game: an accent wash that fades in from the left,
 * and the illustration pinned to the right at the band's full height.
 *
 * Fitting rather than filling is what keeps a wide tile honest — its scene band
 * is barely a third as tall as it is wide, and filling would scale the art to
 * the width and crop away everything but a stripe.
 */
export function GameScene({ game, opacity = 1, washed = true }: GameSceneProps) {
  const scene = gameRegistry[game].scene;
  const asset = gameSceneAssets[scene];

  return (
    <>
      {washed ? (
        <div
          aria-hidden
          className="absolute inset-0"
          style={{
            background: `linear-gradient(to right, transparent 36%, color-mix(in srgb, ${wash[scene]} 82%, transparent) 100%)`,
          }}
        />
      ) : null}
      <Image
        src={asset.src}
        alt=""
        aria-hidden
        fill
        sizes="(min-width: 1024px) 20vw, 50vw"
        className="pointer-events-none select-none object-contain object-right"
        style={opacity === 1 ? undefined : { opacity }}
      />
    </>
  );
}
