import type { ComponentType } from "react";

import {
  ArrowRightIcon,
  AutoAwesomeIcon,
  BasketballIcon,
  BlockIcon,
  BoltIcon,
  BugReportIcon,
  CallSplitIcon,
  CheckIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  CloseIcon,
  CollectionsIcon,
  CompressIcon,
  CricketIcon,
  DangerousIcon,
  DiamondIcon,
  DirectionsRunIcon,
  DoubleArrowUpIcon,
  EditIcon,
  FlagIcon,
  FlameIcon,
  FlashOnIcon,
  FootballIcon,
  FormatListNumberedIcon,
  GlobeIcon,
  GridOnIcon,
  GridViewIcon,
  GroupsIcon,
  HealingIcon,
  HeartIcon,
  HistoryIcon,
  KabaddiIcon,
  InfinityIcon,
  InsightsIcon,
  LightbulbIcon,
  LockIcon,
  MedalIcon,
  MotorsportIcon,
  MyLocationIcon,
  PaidIcon,
  PanToolIcon,
  PersonPinCircleIcon,
  PersonSearchIcon,
  PlayArrowIcon,
  PremiumIcon,
  PsychologyIcon,
  QuizIcon,
  RadarIcon,
  ReplayIcon,
  SavingsIcon,
  ScheduleIcon,
  SearchIcon,
  SellIcon,
  SecurityIcon,
  SendIcon,
  ShareIcon,
  ShieldIcon,
  ShowChartIcon,
  StadiumIcon,
  StarIcon,
  StarOutlineIcon,
  StyleIcon,
  SwapHorizIcon,
  SwipeDownIcon,
  SyncAltIcon,
  TennisIcon,
  TimerIcon,
  TimerOffIcon,
  TrendingUpIcon,
  TuneIcon,
  TrophyIcon,
  TurnRightIcon,
  UTurnLeftIcon,
  VerifiedIcon,
  VerifiedUserIcon,
  VerticalAlignTopIcon,
  VisibilityIcon,
  WarningIcon,
  WhatshotIcon,
} from "./glyphs";
import type { IconProps } from "./icon";

/**
 * Glyphs addressable by name, so data can carry an icon as a string rather than
 * a component. The keys are the Material Symbols names, which is what the card
 * pool already records, so a card's `icon` field crosses over verbatim.
 */
export const glyphRegistry = {
  all_inclusive: InfinityIcon,
  arrow_forward: ArrowRightIcon,
  auto_awesome: AutoAwesomeIcon,
  block: BlockIcon,
  bolt: BoltIcon,
  bug_report: BugReportIcon,
  call_split: CallSplitIcon,
  check: CheckIcon,
  chevron_left: ChevronLeftIcon,
  chevron_right: ChevronRightIcon,
  close: CloseIcon,
  collections_bookmark: CollectionsIcon,
  compress: CompressIcon,
  dangerous: DangerousIcon,
  diamond: DiamondIcon,
  directions_run: DirectionsRunIcon,
  edit: EditIcon,
  emoji_events: TrophyIcon,
  flag: FlagIcon,
  flash_on: FlashOnIcon,
  format_list_numbered: FormatListNumberedIcon,
  grid_on: GridOnIcon,
  grid_view: GridViewIcon,
  groups: GroupsIcon,
  favorite: HeartIcon,
  healing: HealingIcon,
  history: HistoryIcon,
  insights: InsightsIcon,
  keyboard_double_arrow_up: DoubleArrowUpIcon,
  lightbulb: LightbulbIcon,
  lock: LockIcon,
  local_fire_department: FlameIcon,
  military_tech: MedalIcon,
  my_location: MyLocationIcon,
  paid: PaidIcon,
  pan_tool: PanToolIcon,
  person_pin_circle: PersonPinCircleIcon,
  person_search: PersonSearchIcon,
  play_arrow: PlayArrowIcon,
  psychology: PsychologyIcon,
  public: GlobeIcon,
  quiz: QuizIcon,
  radar: RadarIcon,
  replay: ReplayIcon,
  savings: SavingsIcon,
  schedule: ScheduleIcon,
  search: SearchIcon,
  sell: SellIcon,
  security: SecurityIcon,
  send: SendIcon,
  ios_share: ShareIcon,
  shield: ShieldIcon,
  show_chart: ShowChartIcon,
  sports_basketball: BasketballIcon,
  sports_cricket: CricketIcon,
  sports_motorsports: MotorsportIcon,
  sports_kabaddi: KabaddiIcon,
  sports_soccer: FootballIcon,
  sports_tennis: TennisIcon,
  stadium: StadiumIcon,
  star: StarIcon,
  star_outline: StarOutlineIcon,
  style: StyleIcon,
  swap_horiz: SwapHorizIcon,
  swipe_down: SwipeDownIcon,
  sync_alt: SyncAltIcon,
  timer: TimerIcon,
  timer_off: TimerOffIcon,
  trending_up: TrendingUpIcon,
  tune: TuneIcon,
  turn_right: TurnRightIcon,
  u_turn_left: UTurnLeftIcon,
  verified: VerifiedIcon,
  verified_user: VerifiedUserIcon,
  vertical_align_top: VerticalAlignTopIcon,
  visibility: VisibilityIcon,
  warning: WarningIcon,
  whatshot: WhatshotIcon,
  workspace_premium: PremiumIcon,
} as const satisfies Record<string, ComponentType<IconProps>>;

export type GlyphName = keyof typeof glyphRegistry;

export type GlyphProps = IconProps & {
  name: GlyphName;
};

/** Renders a registered glyph by name. */
export function Glyph({ name, ...props }: GlyphProps) {
  const Component = glyphRegistry[name];
  return <Component {...props} />;
}
