export type {
  MatchDetailBoardEntry,
  MatchDetailCommentary,
  MatchDetailData,
  MatchDetailLineup,
  MatchDetailMarket,
  MatchDetailOutcome,
  MatchDetailQuiz,
  MatchDetailQuizState,
  MatchDetailScoreboard,
  MatchDetailStat,
  MatchDetailTimelineEvent,
  MatchLeague,
  SportFixtureCount,
} from "@/domain/matches";
